# Generated by Django 6.0.6 on 2026-06-10 13:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=36, unique=True)),
                ('icon_key', models.CharField(max_length=255)),
            ],
        ),
    ]
