# Generated by Django 6.0.6 on 2026-06-10 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categories',
            table='categories',
        ),
    ]
