# Generated by Django 6.0.6 on 2026-06-18 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bussines',
            old_name='category',
            new_name='category_id',
        ),
    ]
