# Generated by Django 6.0.6 on 2026-06-18 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0002_rename_category_bussines_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bussines',
            name='category_id',
        ),
        migrations.AddField(
            model_name='bussines',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bussines', to='Apis.categories'),
        ),
    ]
