# Generated by Django 6.0.6 on 2026-06-11 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0003_bussines'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bussines',
            table='bussines',
        ),
    ]
