# Generated by Django 6.0.6 on 2026-06-18 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0003_remove_bussines_category_id_bussines_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessimage',
            name='bussines',
            field=models.ForeignKey(db_column='bussines_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Apis.bussines'),
        ),
    ]
