# Generated by Django 6.0.6 on 2026-06-21 00:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0004_alter_businessimage_bussines'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=70, null=True)),
                ('rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reviews/photos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bussines', models.ForeignKey(db_column='bussines_id', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Apis.bussines')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reviews',
                'constraints': [models.UniqueConstraint(fields=('user', 'bussines'), name='unique_review_user_per_business')],
            },
        ),
    ]
