# Generated by Django 6.0.6 on 2026-06-11 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0004_alter_bussines_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bussines',
            old_name='updated_at',
            new_name='update_at',
        ),
    ]
