# Generated by Django 6.0.6 on 2026-06-12 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0005_rename_updated_at_bussines_update_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bussines',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='bussines',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bussines', to='Apis.categories'),
        ),
        migrations.AlterField(
            model_name='bussines',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bussines',
            name='is_verificated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bussines',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
