# Generated by Django 6.0.6 on 2026-06-15 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0007_role_user_alter_bussines_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bussines',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
